name: Deploy Docs
on:
  push:
    branches:
      - Dev
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: docs
      - run: npm run build
        working-directory: docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build
